version: '3.8'
services:
  # web:
  #   build: .
  #   ports:
  #     - '8000:8000'
  #   depends_on:
  #     - pg
  pg:
    image: postgres:latest
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
